
services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:${HOARDER_VERSION:-release}
    container_name: hoarder-web
    restart: unless-stopped
    networks:
      - traefik-net
    depends_on:
      - chrome
      - meilisearch
    volumes:
      - ./data/hoarder-app:/data
    ports:
      - 3449:3000
    # env_file:
    #   - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      # env
      HOARDER_VERSION: ${HOARDER_VERSION}
      NEXTAUTH_SECRET: ${HOARDER_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${HOARDER_NEXTAUTH_URL}
      # crawler
      CRAWLER_FULL_PAGE_SCREENSHOT: ${CRAWLER_FULL_PAGE_SCREENSHOT}
      CRAWLER_NAVIGATE_TIMEOUT_SEC: ${CRAWLER_NAVIGATE_TIMEOUT_SEC}
      CRAWLER_JOB_TIMEOUT_SEC: ${CRAWLER_JOB_TIMEOUT_SEC}
      MAX_ASSET_SIZE_MB: ${MAX_ASSET_SIZE_MB}
      # ollama
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL} 
      INFERENCE_TEXT_MODEL: ${INFERENCE_TEXT_MODEL}
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.horder.rule=Host(`hoarder.home`)" 
      - "traefik.http.routers.horder.entrypoints=websecure" 
      - "traefik.http.routers.horder.tls=true"
      - "traefik.http.services.horder.loadbalancer.server.port=3000"
      # http
      - "traefik.http.routers.horder-insecure.rule=Host(`hoarder.home`)"
      - "traefik.http.routers.horder-insecure.entrypoints=web"


  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: hoarder-chrome
    networks:
      - traefik-net
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    environment:
      # env
      HOARDER_VERSION: ${HOARDER_VERSION}
      NEXTAUTH_SECRET: ${HOARDER_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${HOARDER_NEXTAUTH_URL}
      # crawler
      CRAWLER_FULL_PAGE_SCREENSHOT: ${CRAWLER_FULL_PAGE_SCREENSHOT}
      CRAWLER_NAVIGATE_TIMEOUT_SEC: ${CRAWLER_NAVIGATE_TIMEOUT_SEC}
      CRAWLER_JOB_TIMEOUT_SEC: ${CRAWLER_JOB_TIMEOUT_SEC}
      MAX_ASSET_SIZE_MB: ${MAX_ASSET_SIZE_MB}
      # ollama
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL} 
      INFERENCE_TEXT_MODEL: ${INFERENCE_TEXT_MODEL}

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: hoarder-meili
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - ./data/meilisearch/:/meili_data
    # env_file:
    #   - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
      # env
      HOARDER_VERSION: ${HOARDER_VERSION}
      NEXTAUTH_SECRET: ${HOARDER_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${HOARDER_NEXTAUTH_URL}
      # crawler
      CRAWLER_FULL_PAGE_SCREENSHOT: ${CRAWLER_FULL_PAGE_SCREENSHOT}
      CRAWLER_NAVIGATE_TIMEOUT_SEC: ${CRAWLER_NAVIGATE_TIMEOUT_SEC}
      CRAWLER_JOB_TIMEOUT_SEC: ${CRAWLER_JOB_TIMEOUT_SEC}
      MAX_ASSET_SIZE_MB: ${MAX_ASSET_SIZE_MB}
      # ollama
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL} 
      INFERENCE_TEXT_MODEL: ${INFERENCE_TEXT_MODEL}



networks:
  traefik-net:
    external: true
    name: traefik-net


