services:
  homepage-public:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-public
    networks:
      - traefik-net
    restart: unless-stopped
    ports:
      - 1111:3000
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      # homepage domains
      - HOMEPAGE_VAR_DUCK=${HOMEPAGE_VAR_DUCK}
      - HOMEPAGE_VAR_DUCK_LINK=${HOMEPAGE_VAR_DUCK_LINK}
      - HOMEPAGE_VAR_DUCK_IMMICH=${HOMEPAGE_VAR_DUCK_IMMICH}
      - HOMEPAGE_VAR_DUCK_JELLYSEERR=${HOMEPAGE_VAR_DUCK_JELLYSEERR}
      - HOMEPAGE_VAR_NEXT_DOC=${NEXTCLOUD_DOC}
      - HOMEPAGE_VAR_NEXTCLOUD=${DUCK_NEXT}
      # homepage env vars
      - HOMEPAGE_VAR_JELLY=${HOMEPAGE_VAR_JELLY}
      - HOMEPAGE_VAR_NAVI=${HOMEPAGE_VAR_NAVI}
      - HOMEPAGE_VAR_UPTIME_ROBOT_API=${UPTIME_ROBOT_API}
    volumes:
      - ./homepage/:/app/config # Make sure your local config directory exists
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.homepage-public.rule=Host(`${DUCK_BASE}`)
      - traefik.http.routers.homepage-public.entrypoints=websecure
      - traefik.http.routers.homepage-public.tls=true
      - traefik.http.services.homepage-public.loadbalancer.server.port=3000
      # http
      - traefik.http.routers.homepage-public-insecure.rule=Host(`${DUCK_BASE}`)
      - traefik.http.routers.homepage-public-insecure.entrypoints=web


  # dockerproxy-homepage-public:
  #   image: ghcr.io/tecnativa/docker-socket-proxy:latest
  #   container_name: dockerproxy-homepage-public
  #   networks:
  #     - traefik-net
  #   environment:
  #   - CONTAINERS=1 # Allow access to viewing containers
  #   - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
  #   - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
  #   - POST=0 # Disallow any POST operations (effectively read-only)
  #   # ports:
  #   # - 127.0.0.1:2377:2375
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
  #   restart: unless-stopped


networks:
  traefik-net:
    external: true
    name: traefik-net

