
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2284:2283
    networks:
      - traefik-net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./config.json:${IMMICH_CONFIG_FILE}
      # macbook downloads
      # path bind with syncthing 
      - ~/Private/MacbookDownloads:/mnt/media/macbook-downloads
      - ~/Private/Pictures/OldPhotos:/mnt/media/old-photos
      - ~/Private/Pictures/Other/:/mnt/media/other-photos
      - ~/Public/Pictures/Wallpapers:/mnt/media/wallpapers
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      # adguard domain
      # secure
      - "traefik.http.routers.immich-local.rule=Host(`photos.home.arpa`)"
      - "traefik.http.routers.immich-local.entrypoints=websecure"
      - "traefik.http.routers.immich-local.tls=true"
      # duck dns
      # insecure
      - "traefik.http.routers.immich-local-insecure.rule=Host(`photos.home.arpa`)"
      - "traefik.http.routers.immich-local-insecure.entrypoints=web"
      # https
      - "traefik.http.routers.immich.rule=Host(`${DUCK_IMMICH}`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=myresolver"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      # http
      - "traefik.http.routers.immich-insecure.rule=Host(`${DUCK_IMMICH}`)"
      - "traefik.http.routers.immich-insecure.entrypoints=web"

  immich-machine-learning:
    container_name: immich_machine_learning
    networks:
      - traefik-net
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${docker_data_dir}/immich-machine-learning:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    networks:
      - traefik-net
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    networks:
      - traefik-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${docker_data_dir}/database:/var/lib/postgresql/data
    restart: always

networks:
  traefik-net:
    external: true
    name: traefik-net

