
services:
  webtop:
    # image: lscr.io/linuxserver/webtop:latest
    image: lscr.io/linuxserver/webtop:arch-kde
    container_name: webtop
    networks:
      - traefik-net
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - SUBFOLDER=/ #optional
      # - SUBFOLDER=/webtop #optional
      - TITLE=Arch #optional
      - CUSTOM_USER=${WEBTOP_USER}
      - PASSWORD=${WEBTOP_PASS}
    volumes:
      - ./data:/config
      - /dev/dri:/dev/dri
      # - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3757:3000
      - 3011:3001
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/snd:/dev/snd
    shm_size: "1gb" #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.webtop.rule=Host(`webtop.home`)" 
      - "traefik.http.routers.webtop.entrypoints=websecure"      
      - "traefik.http.routers.webtop.tls=true"     
      - "traefik.http.services.webtop.loadbalancer.server.port=3000"
      # http
      - "traefik.http.routers.webtop-insecure.rule=Host(`webtop.home`)"
      - "traefik.http.routers.webtop-insecure.entrypoints=web"

    # labels:
    #   - traefik.enable=true
    #   # https
    #   - traefik.http.routers.webtop.rule=Host(`${DUCK_BASE}`) && (PathPrefix(`/public`) || PathPrefix(`/webtop`) || PathPrefix(`/vnc`) || PathPrefix(`/webtopaudio`) || PathPrefix(`/websockify`) || PathPrefix(`/files`) || PathPrefix(`/audio`))
    #   - traefik.http.routers.webtop.entrypoints=websecure
    #   - traefik.http.routers.webtop.tls=true
    #   - traefik.http.services.webtop.loadbalancer.server.port=3000
    #   - traefik.http.middlewares.web-strip.stripprefix.prefixes=/webtop
    #   - traefik.http.routers.webtop.middlewares=web-strip
    #   # http
    #   - traefik.http.routers.webtop-insecure.rule=Host(`${DUCK_BASE}`) && (PathPrefix(`/public`) || PathPrefix(`/webtop`) || PathPrefix(`/vnc`) || PathPrefix(`/webtopaudio`) || PathPrefix(`/websockify`) || PathPrefix(`/files`) || PathPrefix(`/audio`))
    #   - traefik.http.routers.webtop-insecure.entrypoints=web
    #   - traefik.http.routers.webtop-insecure.middlewares=web-strip

networks:
  traefik-net:
    external: true
    name: traefik-net

