client:
  insecure: false
  ignore-redirect: false
  timeout: 20s

storage:
  type: sqlite
  path: /data/data.db
  caching: true

alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK}"
    default-alert:
      enabled: true
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 10
      success-threshold: 1

maintenance:
  start: 23:00
  duration: 10h
  timezone: "${TZ}"
  every: 

endpoints:
  # interval services
  - name: homepage
    url: "${GATUS_HOMEPAGE}"
    group: Internal
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: jellyfin
    url: "${GATUS_JELLYFIN}"
    group: Internal
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: nextcloud
    url: "${GATUS_NEXTCLOUD}"
    group: Internal
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: immich
    url: "${GATUS_IMMICH}"
    group: Internal
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: Quran API
    url: "${GATUS_QURAN_API}"
    group: Internal
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord


  # External sites
  - name: google
    url: https://google.com
    group: Public sites
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: youtube
    url: https://youtube.com
    group: Public sites
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: facebook
    url: https://facebook.com
    group: Public sites
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: reddit
    url: https://reddit.com
    group: Public sites
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

