
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - traefik-net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - APP_URL=${DUCK_BOOKSTACK}
      # - APP_URL=/bookstack
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - ./data/bookstack-data/:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.book.rule=Host(`${DUCK_BASE}`) && PathPrefix(`/bookstack`)
      - traefik.http.routers.book.entrypoints=websecure
      - traefik.http.routers.book.tls=true
      - traefik.http.services.book.loadbalancer.server.port=80
      # http
      - traefik.http.routers.book-insecure.rule=Host(`${DUCK_BASE}`) && PathPrefix(`/bookstack`)
      - traefik.http.routers.book-insecure.entrypoints=web


  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    networks:
      - traefik-net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=bookstack
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - ./data/db:/config
    restart: unless-stopped



networks:
  traefik-net:
    external: true
    name: traefik-net

