services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    networks:
      - traefik-net
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3442:3000"
      # - "222:22"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.gitea.rule=Host(`gitea.home`)"      
      - "traefik.http.routers.gitea.entrypoints=websecure"      
      - 'traefik.http.routers.gitea.tls=true'      
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      # http
      - "traefik.http.routers.gitea-insecure.rule=Host(`gitea.home`)"
      - "traefik.http.routers.gitea-insecure.entrypoints=web"

  db:
    image: mysql:8
    container_name: gitea-mysql
    restart: always
    networks:
      - traefik-net
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./data/mysql:/var/lib/mysql


networks:
  traefik-net:
    external: true
    name: traefik-net

