services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    networks:
      - traefik-net
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
    restart: always
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3442:3000"
      # - "222:22"
    labels:
      - "traefik.enable=true"
      # https
      - "traefik.http.routers.gitea.rule=Host(`gitea.home`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - 'traefik.http.routers.gitea.tls=true'
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      # http
      - "traefik.http.routers.gitea-insecure.rule=Host(`gitea.home`)"
      - "traefik.http.routers.gitea-insecure.entrypoints=web"


networks:
  traefik-net:
    external: true
    name: traefik-net

