---
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## If you intend to use stash's DLNA functionality uncomment the below network mode 
    # and comment out the above ports section
    # network_mode: host
    ports:
      - "9995:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      ## Point this at your collection.
      - ~/Private/Stash:/data
      ## sync local time
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      ## Keep configs, scrapers, and plugins here.
      - ./data/stash-data/config:/root/.stash
      ## This is where your stash's metadata lives
      - ./data/stash-data/metadata:/metadata
      ## Any other cache content.
      - ./data/stash-data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./data/stash-data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./data/stash-data/generated:/generated

    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.stash.rule=Host(`stashapp.home`)
      - traefik.http.routers.stash.entrypoints=websecure
      - traefik.http.routers.stash.tls=true
      - traefik.http.services.stash.loadbalancer.server.port=9999
      # http
      - traefik.http.routers.stash-insecure.rule=Host(`stashapp.home`)
      - traefik.http.routers.stash-insecure.entrypoints=web



  # Downloader
  #
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl-private
    # uncomment this if you want downalod through vpn
    # network_mode: "container:gluetun-private"
    restart: always
    ports:
      - 17442:17442
    networks:
      - traefik-net
    # depends_on:
    #   - gluetun
    environment: 
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ./data/youtube-dl/appdata:/app/appdata
      - ./data/youtube-dl/users:/app/users
      # private media bind
      - ~/Private/Stash/youtube-dl:/app/video
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.yt-private.rule=Host(`private-yt.home`)"      
      - "traefik.http.routers.yt-private.entrypoints=websecure"      
      - 'traefik.http.routers.yt-private.tls=true'      
      - "traefik.http.services.yt-private.loadbalancer.server.port=17442"
      # http
      - "traefik.http.routers.yt-private-insecure.rule=Host(`private-yt.home`)"
      - "traefik.http.routers.yt-private-insecure.entrypoints=web"


  # VPN 
  #
  # gluetun:
  #   image: qmcgaw/gluetun:v3
  #   restart: always
  #   container_name: gluetun-private
  #   networks:
  #     - traefik-net
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8888:8888/tcp # HTTP proxy
  #     - 8388:8388/tcp # Shadowsocks
  #     - 8388:8388/udp # Shadowsocks
  #     - 17442:17442
  #     - 2323:27017
  #   volumes:
  #     - ./data/youtube-dl/gluetun:/gluetun
  #   environment:
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - OPENVPN_USER=${VPN_USER}
  #     - OPENVPN_PASSWORD=${VPN_PASS}
  #     - SERVER_COUNTRIES=Japan
  #     - TZ=${TZ}
  #     - UPDATER_PERIOD=



networks:
  traefik-net:
    external: true
    name: traefik-net
