
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## If you intend to use stash's DLNA functionality uncomment the below network mode 
    # and comment out the above ports section
    # network_mode: host
    ports:
      - "9995:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      ## Point this at your collection.
      - ~/storage/private/privateFiles:/data
      ## sync local time
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      ## Keep configs, scrapers, and plugins here.
      - ./data/config:/root/.stash
      ## This is where your stash's metadata lives
      - ./data/metadata:/metadata
      ## Any other cache content.
      - ./data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./data/generated:/generated

    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.stash.rule=Host(`stashapp.home`)
      - traefik.http.routers.stash.entrypoints=websecure
      - traefik.http.routers.stash.tls=true
      - traefik.http.services.stash.loadbalancer.server.port=9999
      # http
      - traefik.http.routers.stash-insecure.rule=Host(`stashapp.home`)
      - traefik.http.routers.stash-insecure.entrypoints=web



networks:
  traefik-net:
    external: true
    name: traefik-net
