---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    networks:
      - traefik-net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - APP_TIMEZONE=${TZ}
      - DISPLAY_TIMEZONE=${TZ}
      - SPEEDTEST_SCHEDULE="0 * * * *"
      - PRUNE_RESULTS_OLDER_THAN=90
      # get server list from here 
      # https://c.speedtest.net/speedtest-servers-static.php
      # my list:
      # 7002 - name="Agartala" country="India" cc="IN" sponsor="BHARAT SANCHAR NIGAM LTD" id="7002" host="bsnlooklaagt.mywire.org:8080"
      # 53548 - name="Cumilla" country="Bangladesh" cc="BD" sponsor="KR-Online" id="53548" host="speedtest.ispwifibd.net:8080"
      # or use docker command
      # docker exec speedtest-tracker php /app/www/artisan app:ookla-list-servers
      - SPEEDTEST_SERVERS="7002,53548"
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEEDTEST_APP_KEY}
      # - DB_HOST= #optional
      # - DB_PORT= #optional
      # - DB_DATABASE= #optional
      # - DB_USERNAME= #optional
      # - DB_PASSWORD= #optional
    volumes:
      - ./data/speed:/config
    ports:
      - 5487:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.speed-test.rule=host(`speed.home.arpa`)"
      - "traefik.http.routers.speed-test.entrypoints=websecure"
      - 'traefik.http.routers.speed-test.tls=true'
      - "traefik.http.services.speed-test.loadbalancer.server.port=80"
      # http
      - "traefik.http.routers.speed-test-insecure.rule=host(`speed.home.arpa`)"
      - "traefik.http.routers.speed-test-insecure.entrypoints=web"


networks:
  traefik-net:
    external: true
    name: traefik-net

