
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: "${UID}:${GID}" # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    networks:
      - traefik-net
    environment:
    # Optional: put your config options customization here. Examples
      # - ND_SCANSCHEDULE: 1h
      # - ND_LOGLEVEL: info  
      # - ND_SESSIONTIMEOUT= 24h
      - ND_BASEURL=/navmusic
      - ND_DEFAULTTHEME="Spotify-ish"
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_APIKEY=${LAST_FM_API_KEY}
      - ND_LASTFM_SECRET=${LAST_FM_SECRET}
    volumes:
      - ./data/navidrome:/data
      - ~/Public/Media/Music/:/music:ro 
    labels:
      - "traefik.enable=true"  
      # adguard domain
      # https
      - "traefik.http.routers.navmusic-local.rule=Host(`music.home`)"
      - "traefik.http.routers.navmusic-local.entrypoints=websecure"
      - "traefik.http.routers.navmusic-local.tls=true"
      # https
      - "traefik.http.routers.navmusic-local-insecure.rule=Host(`music.home`)"
      - "traefik.http.routers.navmusic-local-insecure.entrypoints=web"
      # duck dns
      # https
      # - "traefik.http.routers.nav.rule=(Host(`${DUCK_BASE}`) && PathPrefix(`/navmusic`)) || Host(`music.home`)"      
      - "traefik.http.routers.nav.rule=Host(`${DUCK_BASE}`) && PathPrefix(`/navmusic`)"
      - "traefik.http.routers.nav.entrypoints=websecure"
      - "traefik.http.services.nav.loadbalancer.server.port=4533"      
      - 'traefik.http.routers.nav.tls=true'      
      # http
      # - "traefik.http.routers.nav-insecure.rule=(Host(`${DUCK_BASE}`) && PathPrefix(`/navmusic`)) || Host(`music.home`)"      
      - "traefik.http.routers.nav-insecure.rule=Host(`${DUCK_BASE}`) && PathPrefix(`/navmusic`)"      
      - "traefik.http.routers.nav-insecure.entrypoints=web"
      # glance
      - "glance.name=Navidrome"
      - "glance.icon=si:applemusic"
      - "glance.url=https://${DUCK_BASE}/navmusic"
      - "glance.description=Navidrome"
      - "glance.id=Navidrome"


networks:
  traefik-net:
    external: true
    name: traefik-net

