
services:
  traefik:
    image: traefik:v3.1.3
    container_name: traefik
    restart: always
    # mem_limit: 30m
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ./data/traefikConf:/etc/traefik
      - ./data/letsencrypt:/letsencrypt
      - ./data/logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - traefik-net
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.traefik.rule=Host(`traefik.home`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      # http
      - traefik.http.routers.traefik-insecure.rule=Host(`traefik.home`)
      - traefik.http.routers.traefik-insecure.entrypoints=web






# networks:
#   traefik:
#     name: traefik
#     # external: true
networks:
  traefik-net:
    # external: true
    name: traefik-net




