services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower  
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      # glance
      - "glance.name=watchtower"
      - "glance.icon=si:watchtower"
      - "glance.description=Update container"
      - "glance.id=watchtower"

    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN}
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_RUN_ONCE: "false"
      WATCHTOWER_SCHEDULE: "0 9 * * *"
      WATCHTOWER_NOTIFICATION_REPORT: "true" 
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_DISCORD}
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- with .Report -}}
          {{- if or .Updated .Failed -}}
            {{- range .Updated -}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
            {{- end -}}
            {{- range .Failed -}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- end -}}


networks:
  traefik-net:
    external: true
    name: traefik-net
        

