#!/bin/bash

backup_dir=~/backups/tars/nomieCouchDB

# create dir if not yet created
mkdir -p $backup_dir

nomieData=/home/saurav/docker/compose/nomie6/data/couchdb/

# create data dir backup
tar --directory=$nomieData -cvjSf $backup_dir/nomieCouchDB.tar.bz2 .

# # copy to google drive
rclone copy $backup_dir NextcloudDrive:/backups/nomieCouchDB
