
services:
  openspeed:
    container_name: openspeed
    image: openspeedtest/latest
    ports:
      - 3003:3000
      - 3002:3001
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openspeed.rule=Host(`${DUCK_BASE}`) && ( PathPrefix(`/speed`) || PathPrefix(`/assets/images`) || PathPrefix(`/assets/fonts`) ||  PathPrefix(`/assets/js`)  || PathPrefix(`/assets/css`)  || PathPrefix(`/upload`) || PathPrefix(`/download`) )"
      - "traefik.http.routers.openspeed.entrypoints=websecure"
      - 'traefik.http.routers.openspeed.tls=true'
      - "traefik.http.middlewares.openspeed-strip.stripprefix.prefixes=/speed"
      - "traefik.http.routers.openspeed.middlewares=openspeed-strip"
      - "traefik.http.services.openspeed.loadbalancer.server.port=3000"
      # glance
      - "glance.name=Speed test"
      - "glance.icon=si:speedtest"
      - "glance.url=https://${DUCK_BASE}/speed"
      - "glance.description=Speed test"
      - "glance.id=speed"


networks:
  traefik-net:
    external: true
    name: traefik-net



