
---
services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl-private
    # uncomment this if you want downalod through vpn
    # network_mode: "container:gluetun-private"
    restart: always
    ports:
      - 17442:17442
    networks:
      - traefik-net
    # depends_on:
    #   - gluetun
    environment: 
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ./data/appdata:/app/appdata
      - ./data/users:/app/users
      # private media bind
      - ~/storage/private/privateFiles/youtube-dl:/app/video
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.yt-private.rule=Host(`private-yt.home`)"      
      - "traefik.http.routers.yt-private.entrypoints=websecure"      
      - 'traefik.http.routers.yt-private.tls=true'      
      - "traefik.http.services.yt-private.loadbalancer.server.port=17442"
      # http
      - "traefik.http.routers.yt-private-insecure.rule=Host(`private-yt.home`)"
      - "traefik.http.routers.yt-private-insecure.entrypoints=web"


  # VPN 
  #
  # gluetun:
  #   image: qmcgaw/gluetun:v3
  #   restart: always
  #   container_name: gluetun-private
  #   networks:
  #     - traefik-net
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8888:8888/tcp # HTTP proxy
  #     - 8388:8388/tcp # Shadowsocks
  #     - 8388:8388/udp # Shadowsocks
  #     - 17442:17442
  #     - 2323:27017
  #   volumes:
  #     - ./data/gluetun:/gluetun
  #   environment:
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - OPENVPN_USER=${VPN_USER}
  #     - OPENVPN_PASSWORD=${VPN_PASS}
  #     - SERVER_COUNTRIES=Japan
  #     - TZ=${TZ}
  #     - UPDATER_PERIOD=


networks:
  traefik-net:
    external: true
    name: traefik-net

