---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services


- Welcome:
  - Server uptime:
      href: https://stats.uptimerobot.com/kysMElVCYN/796588674
      icon: https://uptimerobot.com/favicon.ico
      description: Server uptime information to check if server was down
      widget:
          type: uptimerobot
          # fields: ["status", "uptime", "lastDown", "downDuration"]
          fields: ["status", "uptime", "lastDown"]
          url: https://api.uptimerobot.com
          key: {{HOMEPAGE_VAR_UPTIME_ROBOT_API}}

  - Uptime robot:
      href: https://stats.uptimerobot.com/kysMElVCYN
      icon: https://uptimerobot.com/favicon.ico
      description: public status page for domain status

- Entertainment:
  - Jellyfin:
      href: http://{{HOMEPAGE_VAR_DUCK}}/movie
      icon: jellyfin
      description: Watch movie/tv-series!
      # server: my-docker
      # container: jellyfin-public

  - Navidrame:
      href: http://{{HOMEPAGE_VAR_DUCK}}/navmusic
      icon: navidrome
      description: Listen to music
      # server: my-docker
      # container: navidrome

- Files and data:
  - Immich:
      href: http://{{HOMEPAGE_VAR_DUCK_IMMICH}}
      icon: immich
      description: photos
      # server: my-docker
      # container: immich_server

  - Nextcloud:
      href: https://{{HOMEPAGE_VAR_NEXTCLOUD}}
      icon: nextcloud
      description: private files
      # server: my-docker
      # container: filebrowser-private



- Utility:
  - Documentation:
      icon: nextcloud
      href: {{HOMEPAGE_VAR_NEXT_DOC}}
      description: read information here to know more about this server
      # server: my-docker
      # container: bookstack

  - Homepage:
      href: http://192.168.0.120:2222
      icon: google-home
      description: local private homepage
      # server: my-docker
      # container: webtop

