---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey
#
title: Saurav homeserver
theme: dark # or light
color: blue
disableCollapse: true
headerStyle: clean
hideVersion: true
hideErrors: true

layout:
  Welcome:
    style: row
    columns: 2
