
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing-obsidian
    hostname: syncthing 
    networks:
      - traefik-net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ./data/syncthing:/config
      - ./data/obsidianVaults:/obsidianVaults
    ports:
      - 6673:8384
      # - 22000:22000/tcp
      # - 22000:22000/udp
      # - 21027:21027/udp
    restart: unless-stopped


  # obsidian-remote:
  #   image: lscr.io/linuxserver/obsidian:latest
  #   container_name: obsidian-remote
  #   depends_on:
  #     - syncthing
  #     - anysocket-learning
  #   networks:
  #     - traefik-net
  #   security_opt:
  #     - seccomp:unconfined 
  #   environment:
  #     - PUID=${UID}
  #     - PGID=${GID}
  #     - TZ=${TZ}
  #     - FM_HOME=/vaults
  #   volumes:
  #     - ./data/obsidianVaults:/vaults
  #   ports:
  #     - 7889:3000
  #     - 7839:3001
  #   devices:
  #     - /dev/dri:/dev/dri 
  #   shm_size: "1gb"
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"  
  #     # https
  #     - "traefik.http.routers.obsidian-remote.rule=Host(`obsidian.home`)"      
  #     - "traefik.http.routers.obsidian-remote.entrypoints=websecure"      
  #     - 'traefik.http.routers.obsidian-remote.tls=true'      
  #     - "traefik.http.services.obsidian-remote.loadbalancer.server.port=3000"
  #     # http
  #     - "traefik.http.routers.obsidian-remote-insecure.rule=Host(`obsidian.home`)"
  #     - "traefik.http.routers.obsidian-remote-insecure.entrypoints=web"



  anysocket-learning:
    image: lynxaegon/obsidian-anysocket-sync-server
    container_name: anysocket-learning
    restart: always
    depends_on:
      - syncthing
    networks:
      - traefik-net
    ports:
      - 4391:3000
    volumes:
      - ./data/anysocket-learning:/app/data
      - ./data/config-learning.js:/app/config.js
      


networks:
  traefik-net:
    external: true
    name: traefik-net

