# ---
# services:
#   memos:
#     image: neosmemo/memos:stable
#     container_name: memos
#     restart: unless-stopped
#     volumes:
#       - ./data/memos/:/var/opt/memos
#     ports:
#       - 5230:5230
#     networks:
#       - traefik-net
#     labels:
#       - "traefik.enable=true" 
#       # https
#       - "traefik.http.routers.memos.rule=Host(`memos.home.arpa`)"
#       - "traefik.http.routers.memos.entrypoints=websecure"
#       - 'traefik.http.routers.memos.tls=true'
#       - "traefik.http.services.memos.loadbalancer.server.port=5230"
#       # http
#       - "traefik.http.routers.memos-insecure.rule=Host(`memos.home.arpa`)"
#       - "traefik.http.routers.memos-insecure.entrypoints=web"
#
#
# networks:
#   traefik-net:
#     external: true
#     name: traefik-net
#
#
#
#
