#!/bin/bash

backup_dir=~/backups/tars/memos

# create dir if not yet created
mkdir -p $backup_dir

nomieData=/home/saurav/docker/compose/memos/data/memos/

# create data dir backup
tar --directory=$nomieData -cvjSf $backup_dir/memos.tar.bz2 .

# # copy to google drive
rclone copy $backup_dir NextcloudDrive:/backups/memos
