---
services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl
    restart: always
    ports:
      - 8998:17442
    networks:
      - traefik-net
    environment: 
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
      UID: ${UID}
      GID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./data/youtube-dl/appdata:/app/appdata
      - ./data/youtube-dl/users:/app/users
      # private media bind
      - ~/Public/Media/Music/youtube-audio:/app/audio
      - ~/Public/Media/Youtube:/app/video
      - ~/Public/Media/Music/subscriptions-audio:/app/subscriptions
    labels:
      - "traefik.enable=true"
      # https
      - "traefik.http.routers.yt.rule=Host(`youtube-dl.home`)"
      - "traefik.http.routers.yt.entrypoints=websecure"
      - 'traefik.http.routers.yt.tls=true'
      - "traefik.http.services.yt.loadbalancer.server.port=17442"
      # http
      - "traefik.http.routers.yt-insecure.rule=Host(`youtube-dl.home`)"
      - "traefik.http.routers.yt-insecure.entrypoints=web"


networks:
  traefik-net:
    external: true
    name: traefik-net
