---
services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl
    ports:
      - "8998:17442"
    networks:
      - traefik-net
    environment: 
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
      UID: ${UID}
      GID: ${GID}
    restart: unless-stopped
    depends_on:
      - ytdl-mongo-db
    volumes:
      - ./data/subscriptions:/app/subscriptions
      - ./data/users:/app/users
      - ./data/appdata:/app/appdata
      # bind to media dirs
      - ~/storage/public/audio/youtube-dl:/app/audio
      - ~/storage/private/youtube-dl:/app/video
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.yt.rule=Host(`youtube-dl.home`)"      
      - "traefik.http.routers.yt.entrypoints=websecure"      
      - 'traefik.http.routers.yt.tls=true'      
      - "traefik.http.services.yt.loadbalancer.server.port=17442"
      # http
      - "traefik.http.routers.yt-insecure.rule=Host(`youtube-dl.home`)"
      - "traefik.http.routers.yt-insecure.entrypoints=web"



  ytdl-mongo-db:
    image: mongo:4
    container_name: ytdl-mongo-db
    networks:
      - traefik-net
    volumes:
      - ./data/db/:/data/db
    # logging:
    #     driver: "none"          
    restart: unless-stopped



networks:
  traefik-net:
    external: true
    name: traefik-net
