services:
  yaade:
    image: esperotech/yaade:latest
    container_name: yaade
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - 9339:9339
    environment:
      - YAADE_ADMIN_USERNAME=admin
    volumes:
      - ./data/yaade:/app/data
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.yaade.rule=Host(`yaade.home.arap`)"      
      - "traefik.http.routers.yaade.entrypoints=websecure"      
      - 'traefik.http.routers.yaade.tls=true' 
      - "traefik.http.services.yaade.loadbalancer.server.port=9339"
      # http
      - "traefik.http.routers.yaade-insecure.rule=Host(`yaade.home.arpa`)"
      - "traefik.http.routers.yaade-insecure.entrypoints=web"


networks:
  traefik-net:
    external: true
    name: traefik-net

