---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing-private
    hostname: syncthing-private
    # networks:
    #   - traefik-net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ./data/syncthing:/config
      - ~/Private/MacbookDownloads:/Private/MacbookDownloads
      - ~/Public/Media/Music:/Music
      - ~/Public/Books:/Books
    ports:
      - 3673:8384
      # - 22000:22000/tcp
      # - 22000:22000/udp
      # - 21027:21027/udp
    restart: unless-stopped
    labels:
      # glance
      - "glance.name=Syncthing"
      - "glance.icon=si:syncthing"
      - "glance.url=http://192.168.0.120:3673"
      - "glance.description=Syncthing sync"
      - "glance.id=syncthing"


