---
services:
  glance:
    image: ghcr.io/echo-saurav/glance:latest
    container_name: glanceapp
    # pull_policy defines the decisions Compose implementations will make when it starts to pull images. Possible values are:
    # always: Compose always pulls the image from the registry.
    # never: Compose doesn't pull the image from a registry and relies on the platform cached image. If there is no cached image, a failure is reported.
    # missing: Compose pulls the image only if it's not available in the platform cache. (default)
    # build: Compose builds the image. Compose rebuilds the image if it's already present.
    #pull_policy: always
    volumes:
      - ./data/glance.yml:/app/glance.yml
      - ./data/assets:/assets
      # host time setting
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6149:8080
    restart: unless-stopped
    networks:
        - traefik-net
    labels:
      - "traefik.enable=true"
      # https
      - "traefik.http.routers.glanceapp.rule=host(`glanceapp.home.arpa`)"
      - "traefik.http.routers.glanceapp.entrypoints=websecure"
      - 'traefik.http.routers.glanceapp.tls=true'
      - "traefik.http.services.glanceapp.loadbalancer.server.port=8080"
      # http
      - "traefik.http.routers.glanceapp-insecure.rule=host(`glanceapp.home.arpa`)"
      - "traefik.http.routers.glanceapp-insecure.entrypoints=web"


networks:
  traefik-net:
    external: true
    name: traefik-net

